H5PEditor.language.core = {
  missingTranslation: '[번역 누락 :key]',
  loading: '로딩중, 잠시만 기다리세요찾...',
  selectLibrary: 'Select the library you wish to use for your content.',
  unknownFieldPath: '찾을 수 없습니다 ":path".',
  notImageField: '":path" 은(는) 이미지가 아닙니다.',
  notImageOrDimensionsField: '":path" is not an image or dimensions field.',
  requiredProperty: ':property 는 필수항목입니다.',
  onlyNumbers: ':property 는 숫자만 입력할 수 있습니다.',
  exceedsMax: ':property value exceeds the maximum of :max.',
  listExceedsMax: 'The list exceeds the maximum of :max items.',
  belowMin: 'The :property value is below the minimum of :min.',
  listBelowMin: 'The list needs at least :min items for the content to function properly.',
  outOfStep: 'The :property value can only be changed in steps of :step.',
  add: '추가',
  addFile: '파일추가',
  removeFile: '파일삭제',
  confirmRemoval: '정말 삭제하시겠습니까? :type?',
  removeImage: '이미지삭제',
  confirmImageRemoval: '이미지를 삭제합니다. 진행할까요?',
  changeFile: '파일변경',
  changeLibrary: '컨텐츠 타입을 변경하시겠습니까?',
  semanticsError: 'Semantics error: :error',
  missingProperty: 'Field :index is missing its :property property.',
  expandCollapse: '확장/축소',
  addEntity: '추가 :entity',
  tooLong: 'Field value is too long, should contain :max letters or less.',
  invalidFormat: 'Field value contains an invalid format or characters that are forbidden.',
  confirmChangeLibrary: 'By doing this you will lose all work done with the current content type. Are you sure you wish to change content type?',
  moreLibraries: 'h5p.org 에서 <a href="http://h5p.org/content-types-and-applications" target="_blank">more content types</a> 를 찾아보세요',
  commonFields: 'Text overrides and translations',
  commonFieldsDescription: 'Here you can edit settings or translate texts used in this content.',
  uploading: '업로딩, 잠시만 기다리세요...',
  noFollow: 'Cannot follow field ":path".',
  editCopyright: '카피라이트 편집',
  close: '닫기',
  tutorialAvailable: '튜토리얼 가능',
  editMode: '편집모드',
  listLabel: '목록',
  uploadError: '파일 업로드 에러',
  fileToLarge: 'The file you are trying to upload might be too large.',
  unknownFileUploadError: 'Unknown file upload error',
  noSemantics: 'Error, could not load the content type form.',
  editImage: '이미지 편집',
  saveLabel: '저장',
  cancelLabel: '취소',
  resetToOriginalLabel: '원본으로 초기화',
  loadingImageEditor: '이미지 편집기 로딩중, 잠시만 기다리세요...',
  selectFiletoUpload: '업로드할 파일을 선택하세요',
  or: '또는',
  enterAudioUrl: '오디오 소스URL을 입력하세요',
  enterVideoUrl: '비디오 소스URL 또는 유튜브 링크를 입력하세요',
  addVideoDescription: 'H5P supports all external video sources formatted as mp4, webm or ogv, like Vimeo Pro, and has support for YouTube links.',
  insert: '삽입',
  cancel: '취소',
  height: '높이',
  width: '넓이',
  textField: '문자열 필드',
  numberField: '숫자 필드',
  orderItemUp: '위로이동',
  orderItemDown: '아래로이동',
  removeItem: '아이템삭제'
};
